# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "919674b93712bcbbf4978290ffdc6274"
application_url = "https://boxy-shopify-app.onrender.com"
embedded = true
name = "OrderBAPI"
handle = "orderbapi"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders, write_orders, read_customers"

[auth]
redirect_urls = [
  "https://boxy-shopify-app.onrender.com/auth/callback",
  "https://boxy-shopify-app.onrender.com/auth/shopify/callback",
  "https://boxy-shopify-app.onrender.com/api/auth/callback"
]

[pos]
embedded = false
