# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "919674b93712bcbbf4978290ffdc6274"
application_url = "https://nd-diseases-accuracy-slot.trycloudflare.com"
embedded = false
name = "BoxyHelper"
handle = "BoxyHelper"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders, write_orders, read_customers"

[auth]
redirect_urls = [
  "https://nd-diseases-accuracy-slot.trycloudflare.com/auth/callback",
  "https://nd-diseases-accuracy-slot.trycloudflare.com/auth/shopify/callback",
  "https://nd-diseases-accuracy-slot.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
